// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConsoleDom: typeof import('./src/components/components/ConsoleDom.vue')['default']
    Container: typeof import('./src/components/container.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    Everylist: typeof import('./src/components/components/everylist.vue')['default']
    List: typeof import('./src/components/components/list.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
  }
}
